### ISSUE TITLE
Add Technicolor_vcnt-a_ACR-13-18.1.c.0514-950-RB/vcnt-a_ACR-13-18.1.c.0514-950-RB.rbi for DJA0231

### ISSUE THREAD

**Issue by rhettk** [kevdagoat/hack-technicolor#110]
**Important:** Check issue still occurs in [Latest](https://hack-technicolor.readthedocs.io/en/latest/) branch.

Please fill out the following, remembering to put an 'X' in the '[ ]' to mark the checkbox:

**Firmware version**
Technicolor_vcnt-a_ACR-13-18.1.c.0514-950-RB/vcnt-a_ACR-13-18.1.c.0514-950-RB.rbi

**Image Format**

- [x] RBI

**Would you take care of adding this new firmware in the wiki?**

- [ ] Yes! I will take care of that
- [x] No, do it for me, I can't use GitHub...

**Where can we get it?**

- [x] From ISP's url - public
- [ ] From ISP's url - private
- [ ] From own cloud sharing

**Did you manage to root this firmware version already?**

- [X] Yes, following Type 2 instructions

Type: HTTP
Link: http://fwstore.bdms.telstra.net/Technicolor_vcnt-a_ACR-13-18.1.c.0514-950-RB/vcnt-a_ACR-13-18.1.c.0514-950-RB.rbi

**Device Info**
DJA0231.
Board Mnemonic: VCNT-A 
Model Number:DJA0231
Vendor Name/Code: Telstra

**Comment by LuKePicci** [comment]
Done in 24a3ac3 Thanks for confirming strategy #C works.
