### ISSUE TITLE
Custom GUI Bricking Risk Not Explained

### ISSUE THREAD

**Issue by flywire** [kevdagoat/hack-technicolor#15]
[Custom GUI](https://github.com/kevdagoat/hack-technicolor/blame/master/docs/Unlock%20Functionality.md#L44-L49) section.

Gateways have been bricked installing this firmware so risk should be explained.

**Comment by kevdagoat** [comment]
Thanks, all fixed now.

Btw, next time, feel free to fix it yourself if you have the time, you do have collabarator access after all :)
