### ISSUE TITLE
The download server for TIM ACS has changed

### ISSUE THREAD

**Issue by GHOSTS15** [kevdagoat/hack-technicolor#179]
why is this site not working?: https://156.54.126.84/Firmware/TR069/AGThomson/AGTHP_2.2.3_003_CLOSED.rbi

**Comment by FrancYescO** [comment]
probably because you didn't look at the *

**Comment by GHOSTS15** [comment]
I did it, but I didn't understand what it meant. If you know how to solve it please tell me.
p.s temporanemaente I solved (searching well, I found the libraries of a guy), and I found some firmware updates (the latest version 2.3.2) I saw that there were also in this repository but were not updated to the latest version (and by the way not even put in the table of firmware) .... but now my doubt, the firmware is this repository that the other guy (I do not know if I can say the name) are safe? may contain malicious code?

Translated with www.DeepL.com/Translator (free version)

**Comment by FrancYescO** [comment]
Means that you cannot access the link if you have not a TIM Italy IP (and digest username and password).

You can report the name, or where you found things.. idk what you want to do.

**Comment by GHOSTS15** [comment]
I have both the modem TIM and the Italian ip but when I access the site loads a little time and then tells me it is not reachable, the library is ivy_mike (link: https://www.mediafire.com/folder/0jcrqtsri8eaj/ ), found on the guide of hwupgrade (link: https://www.hwupgrade.it/forum/showthread.php?t=2870856 )

**Comment by GHOSTS15** [comment]
@FrancYescO  so?

**Comment by FrancYescO** [comment]
So what? download links are valid but you need credentials and a TIM IP (not italian ip)
just use torrent if are not able to use direct links

**Comment by lorenzocanalelc** [comment]
Actually he is right, the right url now it's https://fw.regman-tl.interbusiness.it:11443/Firmware/TR069/AGThomson/AGTHP_2.2.3_003_CLOSED.rbi, but you still need username and password

**Comment by LuKePicci** [comment]
Feel free to update the URLs on the repo page
________________________________

**Comment by lorenzocanalelc** [comment]
Actually, I don't know why, but now the old link works again... Maybe they where doing some maintenance.

Instead, these link do not work anymore and they are not even in the new server, so they can just be deleted from the list.

http://156.54.126.84/Firmware/TR069/AGThomson/AGTEF_1.0.0_003_closed.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTEF_1.0.0_006_closed.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTEF_1.0.2_001_closed.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTEF_1.0.3_001_closed.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTEF_1.0.4_004_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTEF_1.0.4_005_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTEF_1.1.2_001_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTEF_2.2.0_004_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTEF_2.2.1_001_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTHP_1.0.2_001_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTHP_1.0.2_002_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTHP_1.0.3_001_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTHP_1.0.4_002_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTHP_1.0.5_001_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTHP_1.0.6_001_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTHP_1.1.2_001_CLOSED.rbi
http://156.54.126.84/Firmware/TR069/AGThomson/AGTHP_2.0.1_001_CLOSED.rbi
