### ISSUE TITLE
Does anyone have a rbi file for Technicolor DGA0122/ DGA0122NLK or know how to restore from a raw bank dump?

### ISSUE THREAD

**Issue by protonbeam** [kevdagoat/hack-technicolor#217]
> If there's anyone with UNO uk can you please download and upload the rbi file to the repository from this link: https://help.uno.uk/knowledge-base/article/technicolor-dwa0120 you can only download from within their network. they have other technicolor firmwares aswell.

_Originally posted by @kingpeppermint in https://github.com/hack-technicolor/hack-technicolor/issues/189#issuecomment-1022727912_

Does anyone have a rbi file for Technicolor DGA0122 like above or is there a guide of how to restore 
from a raw bank dump?
https://hack-technicolor.readthedocs.io/en/stable/Repository/#dwa0122-vcnt-2

Thanks

**Comment by LuKePicci** [comment]
Unfortunately nobody from uno.uk shared the RBI, the bank dump is restorable but you need to be root to write the raw image (or use a nand writer on desoldered chip)
________________________________
From: protonbeam ***@***.***>
Sent: Wednesday, March 2, 2022 4:31:35 PM
To: hack-technicolor/hack-technicolor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hack-technicolor/hack-technicolor] Does anyone have a rbi file for Technicolor DGA0122/ DGA0122NLK or know how to restore from a raw bank dump? (Issue #217)


If there's anyone with UNO uk can you please download and upload the rbi file to the repository from this link: https://help.uno.uk/knowledge-base/article/technicolor-dwa0120 you can only download from within their network. they have other technicolor firmwares aswell.

Originally posted by @kingpeppermint<https://github.com/kingpeppermint> in #189 (comment)<https://github.com/hack-technicolor/hack-technicolor/issues/189#issuecomment-1022727912>

Does anyone have a rbi file for Technicolor DGA0122 or is there a guide of how to restore
from a raw bank dump?
https://hack-technicolor.readthedocs.io/en/stable/Repository/#dwa0122-vcnt-2

Thanks

**Comment by protonbeam** [comment]
Thanks for the reply - how do you write as root if the router won't boot I'm thinking of trying to change the booted bank but its hard to find any information on the Technicolor DGA0122 (there isn't even a full manual) on how to do this - do you have any ideas?   

I'm basically trying to find a way to fix what went wrong after I attempted to install tch-nginx-gui = why did it Erase bank_1 and does this router have a bank_2 which can be copied to bank_1.
- https://github.com/Ansuel/tch-nginx-gui/issues/1130 
```
- `root@dsldevice:~# /etc/init.d/rootdevice force
passwd: password for root changed by root
Unlocking /dev/mtd4 ...

Writing from /dev/mtd3 to /dev/mtd4 ...
Unlocking bank_1 ...
Erasing bank_1 ...
Rebooting ...`
```
Thanks

**Comment by protonbeam** [comment]
This video may help give a better idea of what happens when it boots - https://user-images.githubusercontent.com/100783100/156420019-f2deff13-587f-47d6-b7b2-521f5784f5da.mp4

**Comment by kingpeppermint** [comment]
> This video may help give a better idea of what happens when it boots - https://user-images.githubusercontent.com/100783100/156420019-f2deff13-587f-47d6-b7b2-521f5784f5da.mp4

It looks like it's stuck in bootP or in other words, a technicolor router has two banks who in turn have a firmware and a backup firmware, it's failing to boot either.  If you would have an RBI file you can recover it by setting up an dhcp server and offering the RBI file. If not the only option is soldering (opening the router casing, de-soldering the chip and programming it with external tools(the nand writer) as @LuKePicci referred to.

**Comment by protonbeam** [comment]
Thanks for the reply 

so it would try bank_2 before moving onto bootP - does this imply bank_2 is not bootable either?

Does failboot has a chance to still work - (https://hack-technicolor.readthedocs.io/en/stable/Resources/#crazy-power-switching) or is still best to get a serial Adapter to see what the router is doing.

Is there anywhere you can find a rbi file for Technicolor DGA0122 or can create your own?

It looks like I'm not the only 1 this has happened to https://forums.whirlpool.net.au/archive/9xv6j74j maybe we need a don't install tch-nginx-gui on this device list especially it there isn't a widely available rbi file. 

Are there any guides for de-soldering the chip and programming it from a bank dump?

Thanks

**Comment by LuKePicci** [comment]
> so it would try bank_2 before moving onto bootP - does this imply bank_2 is not bootable either?
Exactly. The source of your troubles is the fact that you installed the tch-nginx-gui which automatically implements the "optimal bank plan" as described in out bank planning guide step, where you might have noticed that notable exception warning about the "Missing RBI".

Your current situation is a normal "easy to recover" condition for people who has their board's RBI.
