### ISSUE TITLE
Evaluating Torrent as firmware sharing facility

### ISSUE THREAD

**Issue by LuKePicci** [kevdagoat/hack-technicolor#27]
We have an issue that needs to be addressed sooner or later. We rely on public URL's to download RBI firmwares, and we started archiving "special" firmwares inside this repo itself.
Older URL's may get broken anytime. Whenever this happens, we couldn't rely on this git repo for file storage, otherwise the repo will indefinitely grow up in size, and this is not desirable for a git repo (side note: we also must migrate the current existing firmware folder into git-lfs https://github.com/git-lfs/git-lfs/wiki/Tutorial) and will not fit github disk quota.

My proposal: we could create a single torrent for each RBI, adopting the webseed spec (read here: http://wiki.theory.org/BitTorrentSpecification#WebSeeding), using the original URL we already collected as webseeds. There will be no differences while the URL is still valid, but users may ask for torrent reseed whenever it goes down. Also, rare files with no more valid webseed URL may be uploaded to free torrent seedboxes Torrent metadata files would be hosted here in this repo with no issues, they're small. Of course we can't just store magnets, otherwise reseeding would be impossibile - as you may know you need the full .torrent metadata to reseed..

**Comment by kevdagoat** [comment]
I like this idea. Let me look into it further...

**Comment by nutterthanos** [comment]
i like this idea too.

**Comment by nutterthanos** [comment]
But then how do we upload the firmwares to the torrent site or whatever it will be?

**Comment by LuKePicci** [comment]
Once the torrent file exists, everyone who have tha firmware can reseed if they have the rbi. If you have a rare rbi and you frequently get rested requests maybe you could pen a fee seedbox account (limited bandwidth/storage… it’s ok for small firmware files) and keep it here. We don’t need to seed files for which the http url is still valid as it is still the primary seed for that firmware. Of course, in the lucky case where the files spread across many users over the torrent network the seedbox won't be needed, but it's a bit tpo optimistic assumption.

Da: nutterthanos
Inviato: sabato 20 luglio 2019 03:56
A: kevdagoat/hack-technicolor
Cc: Luca Piccirillo; Author
Oggetto: Re: [kevdagoat/hack-technicolor] Evaluating Torrent as firmwaresharing facility (#27)

But then how do we upload the firmwares to the torrent site or whatever it will be?

**Comment by kevdagoat** [comment]
@LuKePicci 

This one is helpful: https://torrentfreak.com/how-to-create-a-torrent/

**Comment by kevdagoat** [comment]
This would be ideal: https://github.com/skipperbent/easy-torrent-tracker

Time to find a VPS

**Comment by LuKePicci** [comment]
DHT will be enough for us, but if you would really like to host something like that you can do it for free on Azure.

Da: Kevdagoat
Inviato: lunedì 22 luglio 2019 06:51
A: kevdagoat/hack-technicolor
Cc: Luca Piccirillo; Mention
Oggetto: Re: [kevdagoat/hack-technicolor] Evaluating Torrent as firmwaresharing facility (#27)

This would be ideal: https://github.com/skipperbent/easy-torrent-tracker
Time to find a VPS

**Comment by kevdagoat** [comment]
@LuKePicci Try the new torrents :)

**Comment by LuKePicci** [comment]
Three issues:
- I see no web seeds
- I see two trackers into a single group, so only one is used by default, should be separated into two tracker groups to query both of them
- ZIPs can't be reseed, whenever we rebuild a zip we never get the same exact binary so we should consider adding plain RBIs too (not sure how webseeds behave with multi-file torrents, do your evaluations)

**Comment by LuKePicci** [comment]
How it should look like:
![image](https://user-images.githubusercontent.com/8722358/61996347-9a7bda80-b093-11e9-86f8-c34567e3ad31.png)
![image](https://user-images.githubusercontent.com/8722358/61996351-aa93ba00-b093-11e9-8488-6dc5705161d9.png)

**Comment by kevdagoat** [comment]
@lukepicci that’s exactly how it looked like when I made all of them?! There were no zip files and all of the default trackers were left in place

**Comment by LuKePicci** [comment]
- Try removing the torrents from your torrent client, then reimport one and see how it goes. If I do it I get this situation:
![image](https://user-images.githubusercontent.com/8722358/62005070-fc891e00-b12d-11e9-90a1-9d6c4aa76fbc.png)
![image](https://user-images.githubusercontent.com/8722358/62005074-04e15900-b12e-11e9-92ed-d49736c610d5.png)


- - This one has a whitespace in its name:
![image](https://user-images.githubusercontent.com/8722358/62005043-addb8400-b12d-11e9-8bb3-a2484f487768.png)

- Aren't those two zip files?
![image](https://user-images.githubusercontent.com/8722358/62005039-98665a00-b12d-11e9-9346-71ef03d3a492.png)

**Comment by kevdagoat** [comment]
Ok, I see now.
The zips are the bank dumps, although they shouldn’t be in zip format

Sent from Mail for Windows 10

**Comment by LuKePicci** [comment]
Nope, bank dumps are not zipped, they are directly passed into xz, they may suffer the same issue of zip files, I have to check. Just focus on ZIP files for now.

**Comment by kevdagoat** [comment]
I didn’t zip those files though

Sent from Mail for Windows 10

**Comment by LuKePicci** [comment]
I know, they are zipped by uno.uk, that's why we have to decide how to approach them. If we include both the original zip AND the RBIs in the same torrent, such torrents would be at least partially reseedable, we need to check if we could set the webseed to seed only the zip.

**Comment by LuKePicci** [comment]
Oh, one more thing, whenever you end up rebuilding the torrents, add a link to this github repo in the torrent metadata:
![image](https://user-images.githubusercontent.com/8722358/62005267-18da8a00-b131-11e9-9511-6994b1f1fae4.png)

**Comment by LuKePicci** [comment]
I rebuilt one to test, and it works fine, so something was wrong when you created them. Here is how I made it:
![image](https://user-images.githubusercontent.com/8722358/62005440-838cc500-b133-11e9-80b3-10fe00cf47b1.png)

**Comment by kevdagoat** [comment]
Ok, I will do these tomorrow night

**Comment by kevdagoat** [comment]
Ok, @LuKePicci these are done now.

**Comment by LuKePicci** [comment]
Now we need to add links to torrent files in the firmware repo

**Comment by LuKePicci** [comment]
Almost done, I edited all of them in bulk, I hope most of the links are not broken 😅

**Comment by kevdagoat** [comment]
Ok. I was more thinking having a torrent option in the table

**Comment by LuKePicci** [comment]
I migrated every .xz and .rbi file in this repo to LFS, any other file of the same type will be on LFS by default.

**Comment by kevdagoat** [comment]
Ok, all good.

**Comment by kevdagoat** [comment]
I think we can close this now as it has been implemented

**Comment by FrancYescO** [comment]
Here just for a rethinking about this implementation:

At least for firmwares that actually don't have a public direct HTTP URL, cloning it in the firmware dir (root of this repo) will allow to avoid dead torrents and facilitate the delivery using the raw.githubusercontent URL (the needs of a torrent client for a ~32MB file is just boring, and github for files under 100MB is okay also witouth LFS, another alternative is to just attach the zip file in a random comment used as archive and linking it in the docs: this just to avoid to increasing the repo size)

**Comment by LuKePicci** [comment]
Including files in the repo is a no go because it makes very difficult to mantain a loca clone of the docs for editing, we would all have gigabytes of useless files in out drives. We have no dead torrents right now, and I'm really concerned about keeping those files here publicly available, as soon as the collection grows up to a relevant size someone from tch could complain about that.
