### ISSUE TITLE
How to Host this Locally

### ISSUE THREAD

**Issue by flywire** [kevdagoat/hack-technicolor#28]
Win10, Installed `Anaconda Distribution` without selecting any options

1. run `activate base` - does nothing. >- Start Anaconda Prompt from Start menu.

2. Click on `serve.bat` - does nothing. >- Start Anaconda Prompt, change to hack-technicolor directory, run `serve.bat`

**Comment by LuKePicci** [comment]
It's easier if you run it from WSL

**Comment by kevdagoat** [comment]
Images?

Sent from Mail for Windows 10

From: flywire
Sent: Monday, July 22, 2019 6:13 PM
To: kevdagoat/hack-technicolor
Cc: Subscribed
Subject: [kevdagoat/hack-technicolor] How to Host this Locally (#28)

Win10, Installed Anaconda Distribution without selecting any options
1. run activate base - does nothing. >- Start Anaconda Prompt from Start menu.
2. Click on serve.bat - does nothing. >- Start Anaconda Prompt, change to hack-technicolor directory, run serve.bat

**Comment by flywire** [comment]
This works with a default Anaconda3 install in Windows: 

**AnacondaServe.bat**
```
@echo off
rem Default Install ie 'Just Me', default folder, Don't add to path or register as system python
set AnacondaPath=%USERPROFILE%\Anaconda3
call %AnacondaPath%\Scripts\activate.bat %AnacondaPath%
start serve
```

**Comment by kevdagoat** [comment]
Ok, will test and implement

**Comment by flywire** [comment]
https://github.com/kevdagoat/hack-technicolor/commit/03991f246af4b4fc3f7559919dc89244a0d51af8#commitcomment-34468270
