### ISSUE TITLE
FW Repository

### ISSUE THREAD

**Issue by kevdagoat** [kevdagoat/hack-technicolor#3]
- [x] TG-1 Firmware
- [x] Markdown links 
- [x] Overhaul Structure (maybe a table??)

**Comment by LuKePicci** [comment]
https://github.com/kevdagoat/hack-technicolor/blob/master/docs/Firmware%20Repository.md#djn2130--vbnt-j

I have the dump for the first vbnt-j firmware, someone sent it to me reading that announcement, where should I post it in order to be linked into this wiki?

**Comment by kevdagoat** [comment]
@LuKePicci Just created a folder called `firmware` 

You can put it in there and I will link it

**Comment by LuKePicci** [comment]
Should I upload only dumps for not available RBIs or RBIs too?

**Comment by kevdagoat** [comment]
Not available RBI’s

Sent from Mail for Windows 10

**Comment by kevdagoat** [comment]
@LuKePicci Did you amnage to get linkify working? 

If not, can you please remove the files that you created :)

Have an idea using markdown links and tables, will most likely implement sometime next week

**Comment by LuKePicci** [comment]
Nope, I do not intend to spend more time on that feature. Btw it's just a matter of getting that extension installed on RTD if you know someone with little experience on hat ask o I’m.

Inviato dal mio dispositivo Windows 10

Da: Kevdagoat
Inviato: venerdì 14 giugno 2019 13:11
A: kevdagoat/hack-technicolor
Cc: Luca Piccirillo; Mention
Oggetto: Re: [kevdagoat/hack-technicolor] FW Repository (#3)

@LuKePicci Did you amnage to get linkify working?
If not, can you please remove the files that you created :)
Have an idea using markdown links and tables, will most likely implement sometime next week

**Comment by kevdagoat** [comment]
More stuff todo:

- [] Migrate box links to firmware/ directory
