### ISSUE TITLE
TG789vacV2 VANT-6 16.3.8046-ver2.5.3-CRF927-2721031.rbi

### ISSUE THREAD

**Issue by majibow** [kevdagoat/hack-technicolor#31]
Please fill out the following, remembering to put an 'X' in the '[ ]' to mark the checkbox:

**Type**
- [ ] Bank Dump
- [X] URL

**Have you followed formatting?**
- [ ] Yes
- [ ] No
- [X] Please check for me :)

**Bank Dump Info**
- [X] Compressed as rbi
- [ ] Uploaded to firmware/

**URL Info**
- [X] Easily accesible
Type: FTP

**Device Info**

Mnemonic: VANT-6

Model Number: TG789vac v2

URL: ftp://ftp.iinet.net.au/pub/iinet/firmware/TG789vacV2/VANT-6/.2752ae5a/vant-6_16.3.8046-ver2.5.3-CRF927-2721031.rbi

I was just reading the rooting guide out of curiosity and noticed there is a newer version on my TG789... I stumbled across the actual stock firmware URL and thought I'd post it here, to be added.

**Comment by kevdagoat** [comment]
Thanks!

**Comment by majibow** [comment]
No problem, but I see an error in your commit. The order is presumably from oldest to newest.  
Just so you know, this version (2.5.3) is the newest, the version that is labelled ver3.0 is actually 2.2.3.

**Comment by kevdagoat** [comment]
Hmm, interesting. Will look into it
