### ISSUE TITLE
Dump for DJA0231 / VCNT-A

### ISSUE THREAD

**Issue by gavindi** [kevdagoat/hack-technicolor#36]
Please fill out the following, remembering to put an 'X' in the '[ ]' to mark the checkbox:

**Type**
- [x] Bank Dump
- [ ] URL

**Have you followed formatting?**
- [ ] Yes
- [ ] No
- [x] Please check for me :)

**Bank Dump Info**
- [x] Compressed as xz
- [ ] Uploaded to firmware/

**URL Info**
- [x] Easily accesible
Type: http

Can be found here: https://drive.google.com/drive/folders/18xeza1uGHs5SHsBtBL_D5eS7ANsCu1an?usp=sharing

**Device Info**

Mnemonic: Telstra Smart Gen 2 ( Technicolor DJA0231 )

Model Number: DJA0231

Vendor Code: VCNT-A

**Comment by kevdagoat** [comment]
There is only one problem with this dump...

Because it has lots of new features (kernel, daemons, etc) it now is bigger than the 25MB GitHub file limit, so it will have to be hosted elsewhere

**Comment by gavindi** [comment]
Where else can it be hosted?

**Comment by LuKePicci** [comment]
We would need to enable LFS, and migrate them all.

Da: Gavin Graham
Inviato: giovedì 15 agosto 2019 05:16
A: kevdagoat/hack-technicolor
Cc: Subscribed
Oggetto: Re: [kevdagoat/hack-technicolor] Dump for DJA0231 / VCNT-A (#36)

Where else can it be hosted?

**Comment by kevdagoat** [comment]
Don’t know. Will look into this.

For now it is on my google drive

Sent from Mail for Windows 10

**Comment by LuKePicci** [comment]
@gavindi which version is this firmware dump?

**Comment by LuKePicci** [comment]
@gavindi would you like to help us getting the key to extract the RBIs for this board?

**Comment by gavindi** [comment]
Sure, I'm happy to help out. I've previously tries https://github.com/pedro-n-rocha/secr but the module wouldn't load. Just tell me what you need me to do.

**Comment by LuKePicci** [comment]
I've pushed a new module for linux 4.1 in this PR https://github.com/pedro-n-rocha/secr/pull/9 try it

**Comment by gavindi** [comment]
Hi,
Here's the OSCK:
AD8A87E29BE6B6ED72F575C1C80BBD638E7CE95E5BF9824145FD7D042CDA2D79
