### ISSUE TITLE
DJN2130 VBNT-J CRF913-17.2.0284-820-RA.rbi

### ISSUE THREAD

**Issue by nutterthanos** [kevdagoat/hack-technicolor#40]
Please fill out the following, remembering to put an 'X' in the '[ ]' to mark the checkbox:

**Type**
- [ ] Bank Dump
- [X] URL

**Have you followed formatting?**
- [ ] Yes
- [ ] No
- [X] Please check for me :)

**Image Format**
- [ ] Link to Bank Dump (compressed as xz)
- [X] Link to RBI

**Where we can get it**
- [X] From ISP's url - public
- [ ] From ISP's url - private
- [ ] From own cloud sharing

**URL Info**
- [X] Easily accessible
         Type: HTTP

**Device Info**

Board Mnemonic: VBNT-J

Model Number: DJA2130

Vendor Name/Code: Telstra

URL: http://fwstore.bdms.telstra.net/Technicolor_vbnt-j_CRF913-17.2.0284-820-RA/vbnt-j_CRF913-17.2.0284-820-RA.rbi

**Firmware version**
CRF913-17.2.0284-820-RA.rbi

Just noticed that they released this don’t know what root type.

**Comment by LuKePicci** [comment]
done.
