### ISSUE TITLE
Gateway photos and Italian Models

### ISSUE THREAD

**Issue by FrancYescO** [kevdagoat/hack-technicolor#45]
Just to easily identify models, add a few (possibly high res) photos of the models in the wiki

PS. why italians models/firmwares are totally hidden from the wiki? :P

**Comment by kevdagoat** [comment]
I don’t live in Italy + don’t have any modems nor time to document currently

Sent from Mail for Windows 10

From: Francesco M
Sent: Monday, September 9, 2019 6:00 PM
To: kevdagoat/hack-technicolor
Cc: Subscribed
Subject: [kevdagoat/hack-technicolor] Gateway photos (#45)

Just to easily identify models, add a few (possibly high res) photo of the model.
PS. why italians models/firmwares are totally hidden from the wiki? :P

**Comment by flywire** [comment]
If someone from the Italian community wanted to contribute it then it could probably be done fairly easily.

**Comment by LuKePicci** [comment]
Let's define a standard set of photos to include and start collecting them. I would suggest: box, casing (all relevant sides), pcb (optional), stock webui (homepage and version/board about page).
However, consider some devices share the same identical appearance , they still need a different set of photos to avoid ambiguity.

> PS. why italians models/firmwares are totally hidden from the wiki? :P

Only TIM and Fastweb firmwareas are not included yet. I'm almost ready to introduce them. I told @mswhirl to integrate vbnt-k/s root support into AFG, I sent him the custom AFG settings. I have to create torrents for fastweb and TIM (only stable ones...) firmwares, then I have to add them into the wiki, then I will mention vbnt-k/s as compatible with AFG as soon as the upstream AFG release support them. Current Types definition are now fine for  Italian firmwares too, so the guide will be consistent. The only thing I'm missing to prepare the torrents for TIM firmwares is the url from which tim release such files - to use as webseed, even if access is restricted.

**Comment by FrancYescO** [comment]
TIM ACS is protected with basicauth (and idk if webseed url allow it), also if is not made for this i think could be better to host rbi in a dedicated github repo, just to have a consistent (/alternative to the ISP hosting) direct webseed url (raw.github....)

btw my main request is about the idea of adding photos, as this can help a lot to identify a device, expecially to spot differences when they are similar

**Comment by kevdagoat** [comment]
@FrancYescO Multi language support: https://docs.readthedocs.io/en/stable/localization.html

**Comment by kevdagoat** [comment]
I feel like this wiki should be in the scope of all Technicolor modems.

**Comment by LuKePicci** [comment]
I think we included everything from Italy too, and wiki analytics shows traffic from Italy doubled that one from AU xD
