### ISSUE TITLE
Help configuring TG799vac VANT-R for "WE" ISP

### ISSUE THREAD

**Issue by bufce2010** [kevdagoat/hack-technicolor#46]
**I need help configuring TechniColor TG799vac VANT-R**
Until there is a custom GUI for the VANT-R, I'll be have to use a tool to edit the config files,
I have PuTTY, WinSCP.
but I'm not familiar with either them nor linux.

Now, what is the information required about my current ISP "WE", that need to be edited so the router would connect to that ISP

also I'll ask for commands later after collecting those infos

ISP user name is like: `1231521@tedata.net.eg`
password is like: `25624120`

-Before doing anything, I'm trying to backup all configuration to USB drive connected to the router
USB: Kingston_DT101G2_1_3814
File Name: wifi+switch.tar.gz
-but the command is probably wrong :D 
```
root@OpenWrt:~# sysupgrade -i -b of=/mnt/usb/Kingston_DT101G2_1_3814/wifi+switch.tar.gz
bla bla blah
- /tmp/sysupgrade.conffiles 2/78 2% (freezes at 2%)
```

**Comment by LuKePicci** [comment]
> I have PuTTY, WinSCP but I'm not familiar with either them nor linux.
That's all you need as tools
> Now, what is the information required about my current ISP "WE"
> ISP user name is like: 1231521@tedata.net.eg
> password is like: 25624120
I'll now do some guesswork. When ISP gives you user/password they usually require you to setup a PPPoE connection. This solves the first "PPPoE tunnel vs plain DHCP" point. We will bet on PPPoE, as DHCP does not make use of any user/password. Next, we need to know if you will need to select any VLAN for your internet connection, and to which kind of line you are going to connect the router: ADSL or VDSL via integrated modem or anything else via ethernet wan port?
> Before doing anything, I'm trying to backup all configuration to USB drive connected to the router
You were quite close to the correct syntax for settings export via sysupgrade command.
I would rather suggest a different approach:
```bash
cd /overlay
tar -cz -f /mnt/usb/Kingston_DT101G2_1_3814/wifi-switch.tar.gz bank_*`
to restore:
```bash
#to clean up any modification to bank_2 files
rm -rf /overlay/bank_2
# change current directory to /overlay
cd /overlay
# extract bank_2 backup from tar archive
tar -x -f /mnt/usb/Kingston_DT101G2_1_3814/wifi-switch.tar.gz bank_2
```

**Comment by bufce2010** [comment]
> > I have PuTTY, WinSCP but I'm not familiar with either them nor linux.
> 
> That's all you need as tools
> 
> > Now, what is the information required about my current ISP "WE"
> > ISP user name is like: [1231521@tedata.net.eg](mailto:1231521@tedata.net.eg)
> > password is like: 25624120
> 
> I'll now do some guesswork. When ISP gives you user/password they usually require you to setup a PPPoE connection. This solves the first "PPPoE tunnel vs plain DHCP" point. We will bet on PPPoE, as DHCP does not make use of any user/password. Next, we need to know if you will need to select any VLAN for your internet connection, and to which kind of line you are going to connect the router: ADSL or VDSL via integrated modem or anything else via ethernet wan port?
> 
> > Before doing anything, I'm trying to backup all configuration to USB drive connected to the router
> 
> You were quite close to the correct syntax for settings export via sysupgrade command.
> I would rather suggest a different approach:
> 
> ```shell
> cd /overlay
> tar -cz -f /mnt/usb/Kingston_DT101G2_1_3814/wifi-switch.tar.gz bank_*`
> ```
> 
> to restore:
> 
> ```shell
> #to clean up any modification to bank_2 files
> rm -rf /overlay/bank_2
> # change current directory to /overlay
> cd /overlay
> # extract bank_2 backup from tar archive
> tar -x -f /mnt/usb/Kingston_DT101G2_1_3814/wifi-switch.tar.gz bank_2
> ```
> 
> You can also explore all files and folder on the router by configuring WinSCP for a normal SCP connection. Use the same user/password you use for SSH (PuTTY)

I took some screenshots from my home router, ISP is implementing VDSL all over the country. but currently it's ADSL 
![Screenshot_20190910_192506_com android chrome](https://user-images.githubusercontent.com/50169186/64654746-8107d580-d42a-11e9-9430-ad43324c0dc0.jpg)
![Screenshot_20190910_203927_com android chrome](https://user-images.githubusercontent.com/50169186/64654826-ab599300-d42a-11e9-86b3-7935a18726cb.jpg)
![Screenshot_20190910_203700_com android chrome](https://user-images.githubusercontent.com/50169186/64654827-abf22980-d42a-11e9-8e1d-d54aac0b3d2a.jpg)
![Screenshot_20190910_212110](https://user-images.githubusercontent.com/50169186/64654828-abf22980-d42a-11e9-82c2-c8b859f04d0d.jpg)
![Screenshot_20190910_232630](https://user-images.githubusercontent.com/50169186/64654829-ac8ac000-d42a-11e9-9fb0-1902bdc88694.jpg)
![Screenshot_20190911_001058](https://user-images.githubusercontent.com/50169186/64654831-adbbed00-d42a-11e9-9fe4-05a836938c7d.jpg)
![Screenshot_20190911_000901](https://user-images.githubusercontent.com/50169186/64654833-aeed1a00-d42a-11e9-8f3c-239b281bd9d8.jpg)
![Screenshot_20190910_192510_com android chrome](https://user-images.githubusercontent.com/50169186/64654835-b0b6dd80-d42a-11e9-967b-7f6037aa9044.jpg)
![Screenshot_20190910_232417](https://user-images.githubusercontent.com/50169186/64654841-b280a100-d42a-11e9-9173-63778767ff4e.jpg)
![Screenshot_20190910_215844](https://user-images.githubusercontent.com/50169186/64654845-b3b1ce00-d42a-11e9-91f0-bf99b4709721.jpg)
![Screenshot_20190910_192506_com android chrome](https://user-images.githubusercontent.com/50169186/64654852-b7455500-d42a-11e9-85e1-41b420790baf.jpg)
![Screenshot_20190910_204145_com android chrome](https://user-images.githubusercontent.com/50169186/64654857-b9a7af00-d42a-11e9-9d64-bf44d77f89a9.jpg)
![Screenshot_20190911_002123](https://user-images.githubusercontent.com/50169186/64654859-b9a7af00-d42a-11e9-9fe4-da8032f9ed93.jpg)
![Screenshot_20190910_213552](https://user-images.githubusercontent.com/50169186/64654860-b9a7af00-d42a-11e9-9361-0c9172dba104.jpg)
![Screenshot_20190911_001542](https://user-images.githubusercontent.com/50169186/64654861-ba404580-d42a-11e9-9e22-28ccd9f42e82.jpg)
![Screenshot_20190911_001348](https://user-images.githubusercontent.com/50169186/64654867-bf04f980-d42a-11e9-93be-9a0ecdf3f67f.jpg)

**Comment by LuKePicci** [comment]
Awesome. It's a standard PPPoE (plus EoA LLC encapsulation) made on top ATM interface with VPI/VCI 0/35. That's all you need to know to configure.

Here is the list of files you will likely need to edit (via WinSCP) to get connection working.

- /etc/config/wansensing
  - disable wansensing
![image](https://user-images.githubusercontent.com/8722358/64657105-338f6680-d432-11e9-8d10-4c9e596b6069.png)
- /etc/config/xtm
  - it has to contain something like this - add or edit as needed
![image](https://user-images.githubusercontent.com/8722358/64656877-405f8a80-d431-11e9-9842-cca41ec3b3c8.png)
- /etc/config/network
  - it should contain a device section like this
![image](https://user-images.githubusercontent.com/8722358/64656930-80bf0880-d431-11e9-921b-98b01264f21d.png)
  - and a wan interface section like this
![image](https://user-images.githubusercontent.com/8722358/64657075-0cd13000-d432-11e9-8bdc-b9fe1ff650d8.png)

Start whit this few changes, restart the router to see all changes being applied. If you are lucky this will be enough for basic connectivity.

**Comment by bufce2010** [comment]
> Start whit this few changes, restart the router to see all changes being applied. If you are lucky this will be enough for basic connectivity.
 
Thanks for making things look that easy. My friend would take it home after work and test it.

If I may, I have some questions. Hoping not to bother you.
Does this model support (VDSL) -AKA- super speeds advertised by my ISP?
Those commands I've been copying, Are they linux? I'm willing to do a lot of reading and studying

**Comment by bufce2010** [comment]
> * /etc/config/network
> * it should contain a device section like this
>     ![image](https://user-images.githubusercontent.com/8722358/64656930-80bf0880-d431-11e9-921b-98b01264f21d.png)
>   * and a wan interface section like this
>     ![image](https://user-images.githubusercontent.com/8722358/64657075-0cd13000-d432-11e9-8bdc-b9fe1ff650d8.png)


can't find those options in "/etc/config/network"

**Comment by bufce2010** [comment]
Done Editing the comment

**Comment by LuKePicci** [comment]
> Does this model "TG799vac VANT-R" support (VDSL) -AKA- super speeds advertised by my ISP?

Yes, it supports VDSL up to profile 17a, so up to 100 mbit/s line rates.
> Those commands I've been copying, Are they linux? I'm willing to do a lot of reading and studying

Every command you run via the root shell ( `/ :~# command` ) are linux-style shell commands. This device run a Linux OS distribution called OpenWrt (a popular Linux for Wireless routers). The configuration files and options you see in /etc/config are typical of OpenWrt, some of them heve been added by technicolor.
> can't find those options in "/etc/config/network"

There should be some 'wan' section, then whatever option it misses you have to add. For instance, if you have a wan section with proto 'dhcp' then you're probably missing username and password options as they do only apply to 'pppoe'.  Just add the missing one, and (if you would like) clean the others which were specific for 'dhcp', like reqopts and vendorid
> can I make DNS obtained Automatically from ISP,

Sure. The last line (`list dns ...`) adds another additional DNS server to those ones obtained from the ISP. You can just remove that extra line if you want.

**Comment by LuKePicci** [comment]
wwan: is not related

macaddr: should be fine, otherwise just drop that option to pick the right one automatically

dns: are 163.121.128.134 and 135 obtained automatically? if yes, just omit those two lines too

**Comment by LuKePicci** [comment]
Just noticed in telia firmwares 'atm0' is called 'atm_wan' instead. Maybe you had it already in /etc/config/xtm and /etc/config/network files. This shouldn't make any difference. Otherwise, change VPI/VCI of 'atm_wan' and delete 'atm0' device in /etc/config/xtm, and change option ifname of wan section from 'atm0' to 'atm_wan'. in /etc/config/network

**Comment by bufce2010** [comment]
> I would rather suggest a different approach:
> ```shell
> cd /overlay
> tar -cz -f /mnt/usb/Kingston_DT101G2_1_3814/wifi-switch.tar.gz bank_*`
> ```
It's been like this for more than 30 minutes
![image](https://user-images.githubusercontent.com/50169186/64691451-f7d8b900-d492-11e9-82c6-847a89adb914.png)


> Just noticed in telia firmwares 'atm0' is called 'atm_wan' instead. Maybe you had it already in /etc/config/xtm and /etc/config/network files. This shouldn't make any difference. Otherwise, change VPI/VCI of 'atm_wan' and delete 'atm0' device in /etc/config/xtm, and change option ifname of wan section from 'atm0' to 'atm_wan'. in /etc/config/network

You lost me :D 
I've edited"xmt" and modified vpi/vci under 'atm_wan' , there was no atm0 and I didn't add it

![image](https://user-images.githubusercontent.com/50169186/64692717-11c7cb00-d496-11e9-8f63-15f3f11aaff5.png)

![image](https://user-images.githubusercontent.com/50169186/64693171-f01b1380-d496-11e9-9a4a-e3a7bd28c2f7.png)

**Comment by FrancYescO** [comment]
> > I would rather suggest a different approach:
> > ```shell
> > cd /overlay
> > tar -cz -f /mnt/usb/Kingston_DT101G2_1_3814/wifi-switch.tar.gz bank_*`
> > ```
> 
> It's been like this for more than 30 minutes
> ![image](https://user-images.githubusercontent.com/50169186/64691451-f7d8b900-d492-11e9-82c6-847a89adb914.png)
> 
it's doing nothing, the trailing backtick was probably a typo.

**Comment by bufce2010** [comment]
ok
router made a full reset, gonna start over

**Comment by LuKePicci** [comment]
> I've edited"xmt" and modified vpi/vci under 'atm_wan' , there was no atm0 and I didn't add it

Ok, so /etc/config/xtm is fine. In /etc/config/network you need to use 'atm_wan' instead of atm0. I used atm0 in my previous examples but you need to use the same one you have in xtm file.

**Comment by bufce2010** [comment]
> it's doing nothing, the trailing backtick was probably a typo.

**Yep, didn't do anything. but it's OK, I'll do it later.**

---
> > I've edited"xmt" and modified vpi/vci under 'atm_wan' , there was no atm0 and I didn't add it
> 
> Ok, so /etc/config/xtm is fine. In /etc/config/network you need to use 'atm_wan' instead of atm0. I used atm0 in my previous examples but you need to use the same one you have in xtm file.

**router made a full reset, started over, setup wifi and lan**
**please check if something is wrong**
**xtm**

![image](https://user-images.githubusercontent.com/50169186/64700293-e8636b00-d4a6-11e9-8d9e-2158a045bef7.png)

**network**

![image](https://user-images.githubusercontent.com/50169186/64700153-a63a2980-d4a6-11e9-9c6f-7ada865bb354.png)

**Comment by LuKePicci** [comment]
Looks good. make sure wansensing is disabled, save all and reboot. It could be enough to connect.

**Comment by bufce2010** [comment]
> Looks good. make sure wansensing is disabled, save all and reboot. It could be enough to connect.

Crossing fingers already, will get the result tonight

**Comment by bufce2010** [comment]
@LuKePicci
It worked like a charm 💓
I wish I can make LEDs stay on, only status LED is steady. other LEDs flicker only when I press once on status BUTTON. 

Something extra, Can I view router's root via WinSCP remotely when knowing global IP address.

**Comment by bufce2010** [comment]
@LuKePicci
It worked like a charm 💓
I wish I can make LEDs stay on, only status LED is steady. other LEDs flicker only when I press once on status BUTTON. 

Something extra, Can I view router's root via WinSCP remotely when knowing global IP address.

**Comment by FrancYescO** [comment]
uci set ledfw.status_led.enable='0'
________________________________
