### ISSUE TITLE
Torrent problem

### ISSUE THREAD

**Issue by proctologic** [kevdagoat/hack-technicolor#51]
Torrent files dont work 
https://github.com/kevdagoat/hack-technicolor/tree/master/torrents/vant-r

**Comment by LuKePicci** [comment]
Can't see right now, keep your torrent client up, I will later on today.

Inviato dal mio dispositivo Windows 10

Da: proctologic
Inviato: martedì 1 ottobre 2019 09:20
A: kevdagoat/hack-technicolor
Cc: Subscribed
Oggetto: [kevdagoat/hack-technicolor] Torrent problem (#51)

Torrent files dont work
https://github.com/kevdagoat/hack-technicolor/tree/master/torrents/vant-r

**Comment by LuKePicci** [comment]
Let me close this, for now, continue commenting here in case some torrent needs reseed.

**Comment by eathtespagheti** [comment]
Hi I'm trying to download the latest [TG789vac Xtreme 35B](https://hack-technicolor.readthedocs.io/en/stable/Repository/#tg789vac-xtream-35b-vbnt-f) firmware via torrent but seems to be dead

**Comment by LuKePicci** [comment]
check now
