### ISSUE TITLE
TG789MYRvac v2

### ISSUE THREAD

**Issue by stephenc87** [kevdagoat/hack-technicolor#6]
Please fill out the following, remembering to put an 'X' in the '[ ]' to mark the checkbox:

**Type**
- [X] Bank Dump
- [ ] URL

**Have you followed formatting?**
- [ ] Yes
- [ ] No
- [X] Please check for me :)

**Bank Dump Info**
- [X] Compressed as xz
- [ ] Uploaded to firmware/

https://www.pastefile.com/2nJlBY

**URL Info**
- [ ] Easily accesible
Type: <eg. FTP HTTP>

Product Vendor
Technicolor
Product Name
MediaAccess TG789MYRvac v2 HP
Software Version
16.3
Firmware Version
16.3.7190-2761005-20161004084353
Firmware OID
57f34fa94f5105213973abd5
Bootloader Version
2.0.89
Bootloader OID
unknown
Hardware Version
VBNT-L

**Comment by LuKePicci** [comment]
Thank you! Just finished adding to the index. I also see there are some vpn server implemented in there, there is at least openvpn, pptp, l2tp/ipsec including their required drivers for mips devices, looks interesting.

**Comment by kevdagoat** [comment]
@LuKePicci interesting. Any way we could package it up?

**Comment by stephenc87** [comment]
I just took it straight from the modem still exploring it myself but I'd be happy to help with anything else
This stuff should be made public by the Devs, people worked hard for this not to be kept private

**Comment by kevdagoat** [comment]
@stephenc87

What do you mean exactly? The guide?

**Comment by stephenc87** [comment]
I would be happy sharing anything else upon request if I have missed something in my upload, what do you mean about what do I mean lol

**Comment by kevdagoat** [comment]
> This stuff should be made public by the Devs, people worked hard for this not to be kept private

???

**Comment by LuKePicci** [comment]
@kevdagoat you can package it with @BoLaMN tools, however, before installing a possibly not working driver on some different platforms, here is what you should do:

Copy the tun.ko driver from this vbnt-l firmware into /tmp fodler of your device, run insmod tun.ko, run dmesg and see what happens, you should see a couple of lines if it inserted fine. Then you need to see if it gets a kernel panic or not when you start the actual tun interface. Just run `ip tuntap add mode tun tun0` and see if what happens, again, run dmesg to see if any log appears (I actually don't know what should appear if it works 😉). If nothing bad occurred, go ahead.

Now that you know it could really work, just install all openvpn packages and its dependencies, EXCEPT that one with the kmod-tun driver, from official openwrt bcm63xx repository. Just install every userspace apps and libraries, one at time following dependencies order, when it says JUST libc dependencies are missing just force it,, at a certain point it will ask you to install the tun driver as dependency, DON'T DO this, force that package to install ignoring the missing driver dependency.

Here is a guide (in italian) for vbnt-k/-s. DO NOT  FOLLOW that guide literally, it's for arm based devices, and makes use of custom package repo for such devices. Again, use official openwrt mips packages instead. When you understand it all works perfectly, you can consider rebuilding all needed packages from the vbnt-l firmware using tools from BoLaMN, then share the obtained ipk set - just the few ones needed for openvpn - as is, Remember, do not confuse package feeds obtained from sources - like that one BoLaMN provided for arm (userspace-only)  or the official one for mips from openwrt - with repacked ipk obtained from firmware iamges.

Good luck!

**Comment by stephenc87** [comment]
> This stuff should be made public by the Devs, people worked hard for this not to be kept private
> ???
> […](#)
> Sent from my iPhone
> On 8 Jul 2019, at 8:25 am, stephenc87 ***@***.***> wrote: This stuff should be made public by the Devs, people worked hard for this not to be kept private

It's a compliment..... What are you unsure about? You are doing something good, it's just sad that it happens like this, Linux isn't private property!

**Comment by kevdagoat** [comment]
Oh yeah, sorry, tiredness is the thief of brainpower :/

We have contacted SFC and others but are waiting for a response. It is a very sad situation.

Sent from Mail for Windows 10
