### ISSUE TITLE
Non-torrent firmware dumps download issues

### ISSUE THREAD

**Issue by maxexcloo** [kevdagoat/hack-technicolor#69]
Hi, when I try to download vbnt-l_16.3.7190-2761005-bank_dump.xz I get a quota exceeded error - is it possible to host this somewhere else?

**Comment by LuKePicci** [comment]
Dump links were deactivated because of excessive quota usage.

Here is the link you requested: https://github.com/kevdagoat/hack-technicolor/raw/d0e56be5bc62287b02369d1d8721346e9ec23f91/firmware/vbnt-1_18.3.0157-3-2-1-CRF905-bank_dump.xz

**Comment by kevdagoat** [comment]
Due to Git LFS streaming limits, they were moved mainly to torrents.

**Comment by maxexcloo** [comment]
Appreciate the help :)
