### ISSUE TITLE
17.2.0405 - VDNT-O

### ISSUE THREAD

**Issue by wuseman** [kevdagoat/hack-technicolor#73]
Telia Xtream v2

Edit: URL fixed.

https://nr1.nu/technicolor/firmware/VDNT-O/1720405o1901012closed.rbi

**Comment by LuKePicci** [comment]
Added in https://github.com/kevdagoat/hack-technicolor/commit/61f3d04502bbb5e2deb4ba4deb8173fa915c3257
Let me know about the other one when you recover it.

**Comment by wuseman** [comment]
Will do, if I find it I have it somewhere, question is where. I update this issue ASAP i find it cause its somewhere in my archive
