### ISSUE TITLE
Add _VERSION_ for _BOARD_

### ISSUE THREAD

**Issue by realyztic** [kevdagoat/hack-technicolor#84]
Please fill out the following, remembering to put an 'X' in the '[ ]' to mark the checkbox:

**Firmware version**
_VERSION_

**Image Format**

- [x] Bank Dump (compressed as xz)
- [x] RBI

**Would you take care of adding this new firmware in the wiki?**

- [x] Yes! I will take care of that
- [ ] No, do it for me, I can't use GitHub...

**Where can we get it?**

- [x] From ISP's url - public
- [x] From ISP's url - private
- [x] From own cloud sharing

**Did you manage to root this firmware version already?**

- [x] Yes, following Type 2 instructions
- [x] Yes, following Type 1 instructions
- [x] Yes, following Type 3 instructions
- [x] No, I can't root it following instructions from the wiki
- [x] I didn't try

Type: _<eg. FTP HTTP>_

Link: _<PUT LINK HERE>_

**Device Info**

Board Mnemonic: _<eg: VCNT-A for DJA0231TLS>_

Model Number: _<eg: DJA0231 for DJA0231TLS>_

Vendor Name/Code: _<eg: Telstra or TLS for DJA0231TLS>_

**Comment by kevdagoat** [comment]
Umm, what is this? Closing.
