### ISSUE TITLE
Download not working for TG799vac Xtream / VANT-W (Telia - Wifi-router Plus)

### ISSUE THREAD

**Issue by ChrisAcrobat** [kevdagoat/hack-technicolor#88]
https://hack-technicolor.readthedocs.io/en/stable/Repository/#telia-wifi-router-plus
IP 131.116.22.230 does not go anywere.

**Comment by LuKePicci** [comment]
That host is only accessible from Tela management VLAN. Your Telia router has access to that network already. You can use wget from inside the router shell and get them if you have root access ss already. Use torrents otherwise.
________________________________

**Comment by ChrisAcrobat** [comment]
It seems that the torrent does not have any seeders.

**Comment by ChrisAcrobat** [comment]
No I do not have root access, not yet at least.

**Comment by LuKePicci** [comment]
Which one?

**Comment by ChrisAcrobat** [comment]
17.2.0405 https://github.com/kevdagoat/hack-technicolor/blob/master/torrents/vant-w/172405w1441030closed.rbi.torrent?raw=true

**Comment by LuKePicci** [comment]
I see some seeders on opentrackr, keep it queued for a while. Meanwhile go on reading the guide, you should grab the Type2 version as well, let me know if that one needs seeding as well.

**Comment by ChrisAcrobat** [comment]
I got the files from torrent. I was using WebTorrent and didn't realise that worked on a seperated net.
